pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: node:latest
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  build:
    image: node:latest
    commands:
      - yarn build
    secrets: [ ga_id ]

  scp:
    image: appleboy/drone-scp
    host: audri.us
    port: 22
    target: /var/www/audri.us
    source: dist
    strip_components: 1
    secrets: [ ssh_username, ssh_key ]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: master
